Add proper leading mitigations (instead of emphasizing the ignore options)

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -146,12 +146,21 @@ process_output() {
 # Calls the given scanning function at $1, shifts, and passes to it $@.
 # Exit 0 if success, otherwise exit 1 with error message.
 scan_with_fn_or_die() {
+  local entry_pt="$1"; shift
   local fn="$1"; shift
   $fn "$@" && exit 0
   echo >&2
   echo "[ERROR] Matched one or more prohibited patterns" >&2
   echo >&2
   echo "Possible mitigations:" >&2
+  [ "${entry_pt}" = "PRE_COMMIT" ] &&
+    echo "- REMOVE SECRETS FROM FILES ABOVE before committing" >&2
+  [ "${entry_pt}" = "COMMIT_MSG" ] &&
+    echo "- REMOVE SECRETS FROM COMMIT MESSAGE before committing" >&2
+  [ "${entry_pt}" = "PRE_MERGE" ] &&
+    echo "- ABORT MERGE AND REMOVE SECRETS FROM INCOMING BRANCH before re-attempting merge" >&2
+  [ "${entry_pt}" = "SCAN" -o "${entry_pt}" = "SCAN_HISTORY" -o "${entry_pt}" = "PRE_MERGE" ] &&
+    echo "- CONSIDER ROTATING CREDENTIALS since they're already committed and may already have been compromised" >&2
   echo "- Mark false positives as allowed using: git config --add secrets.allowed ..." >&2
   echo "- Mark false positives as allowed by adding regular expressions to .gitallowed at repository's root directory" >&2
   echo "- List your configured patterns: git config --get-all secrets.patterns" >&2
@@ -163,7 +172,7 @@ scan_with_fn_or_die() {
 
 # Scans a commit message, passed in the path to a file.
 commit_msg_hook() {
-  scan_with_fn_or_die "scan" "$1"
+  scan_with_fn_or_die "COMMIT_MSG" "scan" "$1"
 }
 
 # Scans all files that are about to be committed.
@@ -176,7 +185,7 @@ pre_commit_hook() {
   while IFS= read -r file; do
     [ -n "$file" ] && files+=("$file")
   done <<< "$(git diff-index --diff-filter 'ACMU' --name-only --cached $rev --)"
-  scan_with_fn_or_die "scan" "${files[@]}"
+  scan_with_fn_or_die "PRE_COMMIT" "scan" "${files[@]}"
 }
 
 # Determines if merging in a commit will introduce tainted history.
@@ -187,7 +196,7 @@ prepare_commit_msg_hook() {
       local sha="${git_head##*=}"           # Get just the SHA
       local branch=$(git symbolic-ref HEAD) # e.g. refs/heads/master
       local dest="${branch#refs/heads/}"    # cut out "refs/heads"
-      git log "${dest}".."${sha}" -p | scan_with_fn_or_die "scan" -
+      git log "${dest}".."${sha}" -p | scan_with_fn_or_die "PRE_MERGE" "scan" -
       ;;
   esac
 }
@@ -335,8 +344,8 @@ case "${COMMAND}" in
       add_config "secrets.patterns" "$1"
     fi
     ;;
-  --scan) scan_with_fn_or_die "scan" "$@" ;;
-  --scan-history) scan_with_fn_or_die "scan_history" "$@" ;;
+  --scan) scan_with_fn_or_die "SCAN" "scan" "$@" ;;
+  --scan-history) scan_with_fn_or_die "SCAN_HISTORY" "scan_history" "$@" ;;
   --list)
     if [ ${GLOBAL} -eq 1 ]; then
       git config --global --get-regex secrets.*
