Fix wording to be consistent with `git-secrets` command name

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -160,9 +160,9 @@ scan_with_fn_or_die() {
   [ "${entry_pt}" = "PRE_MERGE" ] &&
     echo "- ABORT MERGE AND REMOVE SECRETS FROM INCOMING BRANCH before re-attempting merge" >&2
   [ "${entry_pt}" = "SCAN" -o "${entry_pt}" = "SCAN_HISTORY" -o "${entry_pt}" = "PRE_MERGE" ] &&
-    echo "- CONSIDER ROTATING CREDENTIALS since they're already committed and may already have been compromised" >&2 &&
-    echo "- OR CONSIDER REWRITING BRANCH HISTORY if you cannot rotate the possibly compromised credentials" >&2 &&
-    echo "- ALWAYS TELL THE OWNER OF THE CREDENTIALS if you cannot rotate the possibly compromised credentials" >&2
+    echo "- CONSIDER ROTATING SECRETS since they're already committed and may already have been compromised" >&2 &&
+    echo "- OR CONSIDER REWRITING BRANCH HISTORY if you cannot rotate the possibly compromised secrets" >&2 &&
+    echo "- ALWAYS TELL THE OWNER OF THE SECRETS if you cannot rotate the possibly compromised secrets" >&2
   echo "- Mark false positives as allowed using: git config --add secrets.allowed ..." >&2
   echo "- Mark false positives as allowed by adding regular expressions to .gitallowed at repository's root directory" >&2
   echo "- List your configured patterns: git config --get-all secrets.patterns" >&2
